namespace Launcher.Core.Server;

/// <summary>
/// server.properties 解析/编辑/保存（键值对；注释与空行保留）。常用字段索引 Get/Set。
/// </summary>
public sealed class ServerProperties
{
    private readonly Dictionary<string, string> _values = new(StringComparer.OrdinalIgnoreCase);
    private readonly List<string> _comments = []; // 原始注释/空行（保存时保留）

    /// <summary>全部键（编辑表单遍历用）</summary>
    public IReadOnlyDictionary<string, string> Values => _values;

    public string Get(string key, string fallback = "") => _values.TryGetValue(key, out var v) ? v : fallback;

    public int GetInt(string key, int fallback = 0)
        => int.TryParse(Get(key), out var v) ? v : fallback;

    public bool GetBool(string key, bool fallback = false)
        => bool.TryParse(Get(key), out var v) ? v : fallback;

    public void Set(string key, string value) => _values[key] = value;

    public static ServerProperties Load(string path)
    {
        var props = new ServerProperties();
        if (!File.Exists(path)) return props;
        foreach (var line in File.ReadAllLines(path))
        {
            var trimmed = line.Trim();
            if (trimmed.Length == 0 || trimmed.StartsWith('#'))
            {
                props._comments.Add(line);
                continue;
            }
            var eq = trimmed.IndexOf('=');
            if (eq <= 0) continue;
            props._values[trimmed[..eq].Trim()] = trimmed[(eq + 1)..]; // 不 Trim 值（motd 等含首尾空格有意义）
        }
        return props;
    }

    public void Save(string path)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        var sb = new System.Text.StringBuilder();
        if (_comments.Count == 0)
        {
            sb.AppendLine("#Minecraft server properties");
            sb.AppendLine("#Generated by YanKa Launcher — 图形化编辑后保存");
        }
        else
        {
            foreach (var c in _comments) sb.AppendLine(c); // 保留原注释/空行
        }
        foreach (var (k, v) in _values)
            sb.AppendLine($"{k}={v}");
        File.WriteAllText(path, sb.ToString());
    }
}
